routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'PageController@icons']);
		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'PageController@maps']);
		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'PageController@notifications']);
		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'PageController@rtl']);
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'PageController@typography']);
		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'PageController@upgrade']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::group(['prefix'=>'post'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','PostController@index')->name('indexPost');

	Route::get('create','PostController@create')->name('createPost');

	Route::post('store','PostController@store')->name('storePost');

	Route::get('edit','PostController@edit')->name('editPost');

	Route::post('update','PostController@update')->name('updatePost');

	Route::post('destroy','PostController@destroy')->name('destroyPost');

	Route::get('search','PostController@search')->name('searchPost');

	Route::get('filter','PostController@filter')->name('filterPost');

	Route::post('activate','PostController@activate')->name('activatePost');

	Route::post('slug','PostController@slug')->name('slugPost');

	Route::get('search','PostController@search')->name('searchPost');

	Route::post('temp','PostController@temp')->name('tempPost');
	});
});

Route::group(['prefix'=>'banner'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','BannerController@index')->name('indexBanner');

	Route::get('create','BannerController@create')->name('createBanner');

	Route::post('store','BannerController@store')->name('storeBanner');

	Route::get('edit','BannerController@edit')->name('editBanner');

	Route::post('update','BannerController@update')->name('updateBanner');

	Route::post('destroy','BannerController@destroy')->name('destroyBanner');

	Route::get('search','BannerController@search')->name('searchBanner');

	Route::get('filter','BannerController@filter')->name('filterBanner');

	Route::post('activate','BannerController@activate')->name('activateBanner');
	});
});
Route::group(['prefix'=>'categories'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','CategoriesController@index')->name('indexCategories');

	Route::get('create','CategoriesController@create')->name('createCategories');

	Route::post('store','CategoriesController@store')->name('storeCategories');

	Route::get('edit','CategoriesController@edit')->name('editCategories');

	Route::post('update','CategoriesController@update')->name('updateCategories');

	Route::post('destroy','CategoriesController@destroy')->name('destroyCategories');

	Route::get('search','CategoriesController@search')->name('searchCategories');

	Route::get('filter','CategoriesController@filter')->name('filterCategories');

	Route::post('activate','CategoriesController@activate')->name('activateCategories');
	});
});

Route::group(['prefix'=>'menu'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','MenuController@index')->name('indexMenu');

	// Route::get('create','CategoriesController@create')->name('createCategories');

	// Route::post('store','CategoriesController@store')->name('storeCategories');

	// Route::get('edit','CategoriesController@edit')->name('editCategories');

	// Route::post('update','CategoriesController@update')->name('updateCategories');

	// Route::post('destroy','CategoriesController@destroy')->name('destroyCategories');
	});
});

Route::group(['prefix'=>'elastic'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('search','ElasticsearchController@search')->name('searchElasticsearchController');

	Route::get('init','ElasticsearchController@init')->name('initController');
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        return view('users.index', ['users' => $model->paginate(15)]);
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $model->create($request->merge(['password' => Hash::make($request->get('password'))])->all());

        return redirect()->route('user.index')->withStatus(__('User successfully created.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        if ($user->id == 1) {
            return redirect()->route('user.index');
        }

        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User  $user)
    {
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
        ));

        return redirect()->route('user.index')->withStatus(__('User successfully updated.'));
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        if ($user->id == 1) {
            return abort(403);
        }

        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app', ['page' => __('User Management'), 'pageSlug' => 'users'])

@section('content')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div style="background-color: #f7f2dd;" class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 style="color: black" class="mb-0">{{ __('User Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a style="background-color: #4caf50; color: white; padding: 5px 5px;" href="{{ route('user.index') }}">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div style="background-color: #f7f2dd;" class="card-body">
                        <form method="post" action="{{ route('user.store') }}" autocomplete="off">
                            @csrf

                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label style="color: black" class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input style="color: black" type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required autofocus>
                                    @include('alerts.feedback', ['field' => 'name'])
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label style="color: black" class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input style="color: black" type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email') }}" required>
                                    @include('alerts.feedback', ['field' => 'email'])
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label style="color: black" class="form-control-label" for="input-password">{{ __('Password') }}</label>
                                    <input style="color: black" type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Password') }}" value="" required>
                                    @include('alerts.feedback', ['field' => 'password'])
                                </div>
                                <div class="form-group">
                                    <label style="color: black" class="form-control-label" for="input-password-confirmation">{{ __('Confirm Password') }}</label>
                                    <input style="color: black" type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirm Password') }}" value="" required>
                                </div>

                                <div class="text-center">
                                    <button type="submit" style="background-color: #4caf50; color: white; border: 0px; padding: 8px 8px">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app', ['page' => __('User Management'), 'pageSlug' => 'users'])

@section('content')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card">
                    <div style="background-color: #f7f2dd;" class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 style="color: black;" class="mb-0">{{ __('User Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a style="background-color: #4caf50; color: white; padding: 5px 5px" href="{{ route('user.index') }}" >{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div style="background-color: #f7f2dd;" class="card-body">
                        <form method="post" action="{{ route('user.update', $user) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label style="color: black;" class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input style="color: black;" type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name', $user->name) }}" required autofocus>
                                    @include('alerts.feedback', ['field' => 'name'])
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label style="color: black;" class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input style="color: black;" type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email', $user->email) }}" required>
                                    @include('alerts.feedback', ['field' => 'email'])
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label style="color: black;" class="form-control-label" for="input-password">{{ __('Password') }}</label>
                                    <input style="color: black;" type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Password') }}" value="">
                                    @include('alerts.feedback', ['field' => 'password'])
                                </div>
                                <div class="form-group">
                                    <label style="color: black;" class="form-control-label" for="input-password-confirmation">{{ __('Confirm Password') }}</label>
                                    <input style="color: black;" type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirm Password') }}" value="">
                                </div>

                                <div class="text-center">
                                    <button style="background-color: #4caf50; color: white;" type="submit" class="mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app', ['page' => __('User Management'), 'pageSlug' => 'users'])

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div style="background-color: #f7f2dd;" class="card ">
                <div class="card-header">
                    <div class="row">
                        <div class="col-8">
                            <h4 style="color: black;" class="card-title">{{ __('Users') }}</h4>
                        </div>
                        <div  class="col-4 text-right">
                            <a style=" color: white; background-color: #4CAF50; padding: 12px 12px; border: 0px;" href="{{ route('user.create') }}">{{ __('Add user') }}
                        </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @include('alerts.success')

                    <div class="">
                        <table class="table tablesorter " id="">
                            <thead class=" text-primary">
                                <th style="color: black;" scope="col">{{ __('Name') }}</th>
                                <th style="color: black;"  scope="col">{{ __('Email') }}</th>
                                <th style="color: black;"  scope="col">{{ __('Creation Date') }}</th>
                                <th style="color: black;"  scope="col"></th>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td><p style="color: black;">{{ $user->name }}</p></td>
                                        <td>
                                            <a style="color: green;" href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                                        </td>
                                        <td><p style="color: black;">{{ $user->created_at->format('d/m/Y H:i') }}</p></td>
                                        <td class="text-right">
                                                <div class="dropdown">
                                                    <a style="background-color: #4caf50; padding: 5px 14px; border-radius: 14px; color: white;" class="btn-icon-only" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fas fa-ellipsis-v"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                        @if (auth()->user()->id != $user->id)
                                                            <form action="{{ route('user.destroy', $user) }}" method="post">
                                                                @csrf
                                                                @method('delete')
                                                                <a class="dropdown-item" href="{{ route('user.edit', $user) }}">{{ __('Edit') }}</a>
                                                                <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                                                            {{ __('Delete') }}
                                                                </button>
                                                            </form>
                                                        @else
                                                            <a class="dropdown-item" href="{{ route('profile.edit') }}">{{ __('Edit') }}</a>
                                                        @endif
                                                    </div>
                                                </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer py-4">
                    <nav class="d-flex justify-content-end" aria-label="...">
                        {{ $users->links() }}
                    </nav>
                </div>
            </div>
        </div>
    </div>
@endsection