routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
		Route::get('icons', ['as' => 'pages.icons', 'uses' => 'PageController@icons']);
		Route::get('maps', ['as' => 'pages.maps', 'uses' => 'PageController@maps']);
		Route::get('notifications', ['as' => 'pages.notifications', 'uses' => 'PageController@notifications']);
		Route::get('rtl', ['as' => 'pages.rtl', 'uses' => 'PageController@rtl']);
		Route::get('tables', ['as' => 'pages.tables', 'uses' => 'PageController@tables']);
		Route::get('typography', ['as' => 'pages.typography', 'uses' => 'PageController@typography']);
		Route::get('upgrade', ['as' => 'pages.upgrade', 'uses' => 'PageController@upgrade']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::group(['prefix'=>'post'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','PostController@index')->name('indexPost');

	Route::get('create','PostController@create')->name('createPost');

	Route::post('store','PostController@store')->name('storePost');

	Route::get('edit','PostController@edit')->name('editPost');

	Route::post('update','PostController@update')->name('updatePost');

	Route::post('destroy','PostController@destroy')->name('destroyPost');

	Route::get('search','PostController@search')->name('searchPost');

	Route::get('filter','PostController@filter')->name('filterPost');

	Route::post('activate','PostController@activate')->name('activatePost');

	Route::post('slug','PostController@slug')->name('slugPost');

	Route::get('search','PostController@search')->name('searchPost');

	Route::post('temp','PostController@temp')->name('tempPost');
	});
});

Route::group(['prefix'=>'banner'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','BannerController@index')->name('indexBanner');

	Route::get('create','BannerController@create')->name('createBanner');

	Route::post('store','BannerController@store')->name('storeBanner');

	Route::get('edit','BannerController@edit')->name('editBanner');

	Route::post('update','BannerController@update')->name('updateBanner');

	Route::post('destroy','BannerController@destroy')->name('destroyBanner');

	Route::get('search','BannerController@search')->name('searchBanner');

	Route::get('filter','BannerController@filter')->name('filterBanner');

	Route::post('activate','BannerController@activate')->name('activateBanner');
	});
});
Route::group(['prefix'=>'categories'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','CategoriesController@index')->name('indexCategories');

	Route::get('create','CategoriesController@create')->name('createCategories');

	Route::post('store','CategoriesController@store')->name('storeCategories');

	Route::get('edit','CategoriesController@edit')->name('editCategories');

	Route::post('update','CategoriesController@update')->name('updateCategories');

	Route::post('destroy','CategoriesController@destroy')->name('destroyCategories');

	Route::get('search','CategoriesController@search')->name('searchCategories');

	Route::get('filter','CategoriesController@filter')->name('filterCategories');

	Route::post('activate','CategoriesController@activate')->name('activateCategories');
	});
});

Route::group(['prefix'=>'menu'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('index','MenuController@index')->name('indexMenu');

	// Route::get('create','CategoriesController@create')->name('createCategories');

	// Route::post('store','CategoriesController@store')->name('storeCategories');

	// Route::get('edit','CategoriesController@edit')->name('editCategories');

	// Route::post('update','CategoriesController@update')->name('updateCategories');

	// Route::post('destroy','CategoriesController@destroy')->name('destroyCategories');
	});
});

Route::group(['prefix'=>'elastic'], function () {
	Route::group(['middleware' => 'auth'], function () {

	Route::get('search','ElasticsearchController@search')->name('searchElasticsearchController');

	Route::get('init','ElasticsearchController@init')->name('initController');
	});
});

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth

@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-wrapper">
       
        <ul class="nav">
            <li @if ($pageSlug == 'dashboard') class="active " @endif>
                <a href="{{ route('home') }}">
                    <i class="tim-icons icon-chart-pie-36"></i>
                    <p>{{ _('Trang chủ') }}</p>
                </a>
            </li>
            <li @if ($pageSlug == 'menu') class="active " @endif>
                <a href="{{ route('indexMenu') }}">
                    <i class="tim-icons icon-bullet-list-67"></i>
                    <p>{{ _('Menu') }}</p>
                </a>
            </li>
            <li>
                <a data-toggle="collapse" href="#laravel-examples" aria-expanded="true">
                    <i class="fab fa-laravel" ></i>
                    <span class="nav-link-text" >{{ __('Người dùng') }}</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse show" id="laravel-examples">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug == 'profile') class="active " @endif>
                            <a href="{{ route('profile.edit')  }}">
                                <i class="tim-icons icon-single-02"></i>
                                <p>{{ _('User Profile') }}</p>
                            </a>
                        </li>
                        <li @if ($pageSlug == 'users') class="active " @endif>
                            <a href="{{ route('user.index')  }}">
                                <i class="tim-icons icon-badge"></i>
                                <p>{{ _('User Management') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
             <li @if ($pageSlug == 'banner') class="active " @endif>
                <a data-toggle="collapse" href="#banner" aria-expanded="true">
                    <i class="fab fa-laravel tim-icons icon-single-copy-04" ></i>
                    <span class="nav-link-text" >{{ __('Banner') }}</span>
                    <b class="caret mt-1"></b>
                </a>
                <div class="collapse show" id="banner">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug == 'banner') class="active " @endif>
                            <a href="{{ route('createBanner')  }}">
                                <i class="tim-icons icon-single-02"></i>
                                <p>{{ _('Viết Banner') }}</p>
                            </a>
                        </li>
                        <li @if ($pageSlug == 'banner') class="active " @endif>
                            <a href="{{ route('indexBanner')  }}">
                                <i class="tim-icons icon-badge"></i>
                                <p>{{ _('Danh Sách Banner') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li @if ($pageSlug == 'post') class="active " @endif>
                 <a data-toggle="collapse" href="#post" aria-expanded="true">
                    <i class="fab fa-laravel tim-icons icon-align-left-2" ></i>
                    <span class="nav-link-text" >{{ __('Bài Viết') }}</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse show" id="post">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug == 'post') class="active " @endif>
                            <a href="{{ route('createPost')  }}">
                                <i class="tim-icons icon-single-02"></i>
                                <p>{{ _('Thêm bài viết') }}</p>
                            </a>
                        </li>
                        <li @if ($pageSlug == 'post') class="active " @endif>
                            <a href="{{ route('indexPost')  }}">
                                <i class="tim-icons icon-badge"></i>
                                <p>{{ _('Danh sách Bài Viết') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li @if ($pageSlug == 'categories') class="active " @endif>
                 <a data-toggle="collapse" href="#categories" aria-expanded="true">
                    <i class="fab fa-laravel tim-icons icon-align-left-2" ></i>
                    <span class="nav-link-text" >{{ __('Chuyên Mục Tin') }}</span>
                    <b class="caret mt-1"></b>
                </a>
                <div class="collapse show" id="categories">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug == 'categories') class="active " @endif>
                            <a href="{{ route('createCategories')  }}">
                                <i class="tim-icons icon-single-02"></i>
                                <p>{{ _('Thêm Mục Tin') }}</p>
                            </a>
                        </li>
                        <li @if ($pageSlug == 'categories') class="active " @endif>
                            <a href="{{ route('indexCategories')  }}">
                                <i class="tim-icons icon-badge"></i>
                                <p>{{ _('Danh Mục Tin') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li @if ($pageSlug == 'icons') class="active " @endif>
                <a href="{{ route('pages.icons') }}">
                    <i class="tim-icons icon-atom"></i>
                    <p>{{ _('Icons') }}</p>
                </a>
            </li>
            {{-- <li @if ($pageSlug == 'maps') class="active " @endif>
                <a href="{{ route('pages.maps') }}">
                    <i class="tim-icons icon-pin"></i>
                    <p>{{ _('Maps') }}</p>
                </a>
            </li> --}}
            {{-- <li @if ($pageSlug == 'notifications') class="active " @endif>
                <a href="{{ route('pages.notifications') }}">
                    <i class="tim-icons icon-bell-55"></i>
                    <p>{{ _('Notifications') }}</p>
                </a>
            </li> --}}
            {{-- <li @if ($pageSlug == 'tables') class="active " @endif>
                <a href="{{ route('pages.tables') }}">
                    <i class="tim-icons icon-puzzle-10"></i>
                    <p>{{ _('Table List') }}</p>
                </a>
            </li> --}}
            {{-- <li @if ($pageSlug == 'typography') class="active " @endif>
                <a href="{{ route('pages.typography') }}">
                    <i class="tim-icons icon-align-center"></i>
                    <p>{{ _('Typography') }}</p>
                </a>
            </li> --}}
            <li @if ($pageSlug == 'rtl') class="active " @endif>
                <a href="{{ route('pages.rtl') }}">
                    <i class="tim-icons icon-world"></i>
                    <p>{{ _('RTL Support') }}</p>
                </a>
            </li>
            <li class=" {{ $pageSlug == 'upgrade' ? 'active' : '' }}">
                <a href="{{ route('pages.upgrade') }}">
                    <i class="tim-icons icon-spaceship"></i>
                    <p>{{ _('Upgrade to PRO') }}</p>
                </a>
            </li>
        </ul>
    </div>
</div>